{{- if .Values.global.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "urule.serviceAccountName" . }}
  labels:
    {{- include "urule.labels" . | nindent 4 }}
{{- end }}
